apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-request-counter
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: fastapi-request-counter
  template:
    metadata:
      labels:
        app: fastapi-request-counter
    spec:
       containers:
        - name: fastapi-request-counter
          image: fastapi-request-counter:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "sqlite:///./requests.db"  

