apiVersion: v1
kind: Service
metadata:
  name: fastapi-request-counter-service
spec:
  type: NodePort
  selector:
    app: fastapi-request-counter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
